### PR TITLE
Updated Protocol

### PR DESCRIPTION
**Pull request by kanurag94**
Updated protocol to use https always, since django doesn't seem to support it

### CODE REVIEW

**Comment by kumarprafful** [comment]
@kanurag94 instead of hardcoding 'https' you can pass it from the view itself. Try passing protocol from the activate_email view.

**Comment by kanurag94** [comment]
@kumarprafful I don't see any bad points if auto redirect is set for http to https

or can we use
{% if request.is_secure %}HTTPS{% else %}HTTP{% endif %}
to handle this?

The site is supposed to handle http &/s only or else?

**Comment by kanurag94** [comment]
@kumarprafful  we would need to use RequestContext, I am not sure how to use that in django 2. Help appreciated

**Comment by kumarprafful** [comment]
@kanurag94 we are using django 1.11. And your above code is correct.
(just use lowercase, uppercase won't look that good in an email URL)

**Pull request merged**
