### PR TITLE
A little UX/UI change in post_detail_single template

### PR DESCRIPTION
**Pull request by silent-lad**
You can see that if no image is uploaded along with the post it says:-
screen shot 2018-09-06 at 3 46 01 pm

Although it should not display the image section altogether..
So As a work around i replaced **Image not found** with **The title of the post**

### CODE REVIEW

**Comment by kumarprafful** [comment]
@silent-lad Nice work. I would recommend you to remove the text altogether if there is no image found.

**Comment by silent-lad** [comment]
@kumarprafful I made the recommended changes. The picture is shown if it exists and the whole block is hidden if the image doesn't exists.

**Comment by kumarprafful** [comment]
@silent-lad Please don' t make too much of unnecessary changes in the files. Kindly just change the necessary portion.

**Comment by silent-lad** [comment]
@kumarprafful I just **removed the concerned line** ,all other changes must be my code editor inserting tab or spaces due to the prettier plugin. Sorry.

**Comment by kumarprafful** [comment]
@silent-lad Your code has some problem with if conditions. For the time being, I am closing this request. Please test the code beforehand.

**Pull request closed without merging**
